version: '3'
services:
  php:
    build: .
#    image: php:7.4-fpm
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8088:8088"
    volumes:
      - './src/:/var/www/html'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'
      - './src/:/usr/share/nginx/html'
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maindb
      MYSQL_PASSWORD: root
#    networks:
#      - mysql

#networks:
#  mysql:
#    driver: bridge

volumes:
  db_data:
